[supabase]
url = "https://vhkmarcycwdzxjclyyay.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoa21hcmN5Y3dkenhqY2x5eWF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5NDAxNjksImV4cCI6MjA3NjUxNjE2OX0.qnbeq_tfecG6ksr8KKlCAgh2z9j4tIk2TvZTgprGll4"
